//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp4
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.UserOrder = new HashSet<UserOrder>();
        }
    
        public int ID_User { get; set; }
        public string Name { get; set; }
        public string Second_Name { get; set; }
        public string Phone { get; set; }
        public Nullable<int> ID_Role { get; set; }
        public string Login { get; set; }
        public string Pass { get; set; }
        public User (string id_user, string name_user, string sname_user, string phone, string id_role, string login_user, string pass_user)
        {
            ID_User = int.Parse(id_user);
            Name = name_user;
            Second_Name = sname_user;
            Phone = phone;
            ID_Role = int.Parse(id_role);
            Login = login_user;
            Pass = pass_user;
        }
       
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserOrder> UserOrder { get; set; }
    }
}
